version: '3'
services:
  web:
    container_name: ${PROJECT_NAME}_web
    build: ./nginx
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    container_name: ${PROJECT_NAME}_php-fpm
    build: ./php-fpm
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ../:/var/www/

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:5.7.19
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  kvs:
    container_name: ${PROJECT_NAME}_kvs
    image: redis:alpine

volumes:
  db-data:
