version: '3'
services:
  nginx:
    container_name: ${APP_NAME}_nginx
    build: ./nginx
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    build: ./php-fpm
    depends_on:
      - mysql
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    volumes:
      - ../:/var/www/

  mysql:
    container_name: ${APP_NAME}_mysql
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    container_name: ${APP_NAME}_redis
    image: redis:alpine