version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    container_name: "web"
    volumes:
      - ./www:/var/www
    ports:
      - "8080:80"

  app:
    build: ./php
    container_name: "app"

  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=skelton"
    ports:
      - "3306:3306"
