version: '3'
services:
  web:
    image: ./nginx
    container_name: web
    depends_on:
      - app
    volumes:
      - ./www/html:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    build: ./app
    container_name: app
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./www/html:/var/www/html

  db:
    image: mysql:5.7.19
    container_name: db
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
      - ./db/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db-data:
